import {
  Anchor,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BedDouble,
  CalendarCheck2,
  CalendarDays,
  Camera,
  Car,
  Check,
  ChevronDown,
  ChevronUp,
  CircleCheck,
  CircleDollarSign,
  CircleUserRound,
  CircleX,
  Church,
  Clock,
  Compass,
  Copy,
  CreditCard,
  Fish,
  Gem,
  GripVertical,
  Handshake,
  Heart,
  Hourglass,
  Info,
  Landmark,
  Link2,
  ListChecks,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircleQuestionMark,
  MessageSquare,
  Minus,
  Mountain,
  Music,
  PartyPopper,
  Phone,
  PiggyBank,
  Plus,
  Printer,
  RotateCcw,
  Save,
  Send,
  Share2,
  Ship,
  ShoppingBag,
  SlidersHorizontal,
  Sparkle,
  Sparkles,
  Star,
  Tag,
  TriangleAlert,
  Umbrella,
  UserPlus,
  Users,
  UtensilsCrossed,
  Vote,
  Wallet,
  WavesHorizontal,
  X,
  type LucideProps,
} from "lucide-react";
import { InstagramGlyph, FacebookGlyph } from "@/components/BrandGlyphs";

// A curated, tree-shakeable icon map. lucide-react no longer ships brand
// logos (Instagram/Facebook), so those fall back to small inline glyphs, and
// a couple of names below are aliased to their current lucide export.
// When a new icon is needed elsewhere in the app, import it above and add it
// here — avoid `import { icons } from "lucide-react"`, which bundles the
// entire icon set into every page that touches it.
const iconMap = {
  Anchor,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BedDouble,
  CalendarCheck2,
  CalendarDays,
  Camera,
  Car,
  Check,
  CheckCircle2: CircleCheck,
  ChevronDown,
  ChevronUp,
  CircleDollarSign,
  CircleUserRound,
  Church,
  Clock,
  Compass,
  Copy,
  CreditCard,
  Fish,
  Gem,
  GripVertical,
  Handshake,
  Heart,
  Hourglass,
  Info,
  Landmark,
  Link2,
  ListChecks,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircleQuestionMark,
  MessageSquare,
  Minus,
  Mountain,
  Music,
  PartyPopper,
  Phone,
  PiggyBank,
  Plus,
  Printer,
  RotateCcw,
  Save,
  Send,
  Share2,
  Ship,
  ShoppingBag,
  SlidersHorizontal,
  Sparkle,
  Sparkles,
  Star,
  Tag,
  TriangleAlert,
  Umbrella,
  UserPlus,
  Users,
  UtensilsCrossed,
  Vote,
  Wallet,
  Waves: WavesHorizontal,
  X,
  XCircle: CircleX,
};

export type IconName = keyof typeof iconMap | "Instagram" | "Facebook";

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  if (name === "Instagram") return <InstagramGlyph {...props} />;
  if (name === "Facebook") return <FacebookGlyph {...props} />;
  const LucideIcon = iconMap[name as keyof typeof iconMap];
  if (!LucideIcon) return null;
  return <LucideIcon {...props} />;
}
